### ISSUE TITLE
motor rotations per foot scaling

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#10]
the scaling seems to be working properly, but it would be great if changing the motor rotations/ft in the UI didn't change the set position value and the soft limit value.  It makes sense that it would change the current position but it is confusing to be setting up an axis and change this value then have to reset your soft limits and set position values.

**Comment by francotiveron** [comment]
rotation/foot impact on positions have been reversed for Set Position, Soft Limit Up and Soft Limit Down
