### ISSUE TITLE
selecting grouped axes in a move command

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#11]
Currently I am able to add a grouped axes when filling out a move command and we shouldn't be able to.  For example, If I have axis 1 and 2 assigned to group 1 and swipe right on axis 3 to create a move, I can then add axis 1 to that move.  It will not actually move when I press the run button but still shows that the move is assigned.

**Comment by francotiveron** [comment]
Fixed - grouped motors do not display in the check box grid in the motion page
