### ISSUE TITLE
text boxes should automatically overwrite

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#12]
Text boxes should automatically overwrite when selected.  I know a choice was made to keep the old values but I am finding myself clearing them nearly every time.  Sometimes the existing info is useful so it would be great if possible that the text is just automatically highlighted so a user can just start typing or choose to press next and keep the existing info

**Comment by francotiveron** [comment]
New behaviour
When a new element is selected for editing, the pad textbox content is fully highlighted (SelectAll), then
- A value button (numeric or alpha) is pressed => text fully replaced with new key
- A non-value button is pressed or the textbox is tapped so to reset selection => new key is simply appended (original behaviour)
