### ISSUE TITLE
Preset button colors

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#14]
We would like to see a little more clarity in the colors of the preset buttons.  we are thinking:

- grayed if not programed
- dark blue when programed
- highlighted blue when selected
- green when moving

The big changes here are that they are gray when empty and green when moving.  I understand the green when moving might be difficult since axes are now clearing their moves when they complete so if that is not possible, it isn't a huge deal

**Comment by francotiveron** [comment]
Implemented
1) Empty Preset color is Gray
2) Non Empty Preset color is Dark Blue,
3) Clicking on Preset uploads to PLC and sets Preset_loaded tag,  color changes light blue
4) When light blue, if motion is detected the color is Green
5) Two events make the Preset return to status 2 (non empty + non uploaded):
5.1) PLC sets tag Preset_Complete
5.2) User clicks on Clear (motion) button
