### ISSUE TITLE
Pop-up message themeing

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#15]
It would be great if the pop up warning messages can match the overall theme of the rest of the project.  these are very useful, it is just a little jarring when they look like a different windows application.  Also, it would be great if we can have a more clear indication of a lost watchdog.

**Comment by francotiveron** [comment]
Message Popups changed to look more like in the Figma design.
Please have a look and feel free to give more detailed feedback is needed. Look-and-feel UI/UX matters are usually quite subjective

**Comment by francotiveron** [comment]
Re-design Popups according to Figma

**Comment by francotiveron** [comment]
Please confirm that the wanted theme is the one in Figma

**Comment by francotiveron** [comment]
- Info Popup
![image](https://user-images.githubusercontent.com/8280970/84560313-0d627280-ad86-11ea-8520-4987365af9ef.png)
-Warning Popup
![image](https://user-images.githubusercontent.com/8280970/84560385-d476cd80-ad86-11ea-883c-e2b1d28d0173.png)
-Error Popup
![image](https://user-images.githubusercontent.com/8280970/84560418-320b1a00-ad87-11ea-9e7d-a7cd3c536684.png)

**Comment by francotiveron** [comment]
Complete
