### ISSUE TITLE
Axis selection alignment in moves and cues

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#20]
I know you said the next version has the fix for not being able to select grouped axes, so that will be great.  we would also like to see if there is a way to keep everything aligned a little better.  currently if we rename an axis its alignment to the rest of the axes in the selection page is off depending on the numbers of characters

**Comment by francotiveron** [comment]
Couldn't see any misalignment in my tests. Please add screenshots

**Comment by pkelm1** [comment]
I am not at my computer right now, but on mine if I change a couple of axis names, then go into a move command, the axis names on the bottom where you can select other axes are out of alignment since they are have different length names

**Comment by francotiveron** [comment]
Fixed
Changed check box alignment in  motion page from center to left
