### ISSUE TITLE
Add user enable bit to each axis

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#22]
I am going to add a bit GVL.Axis_XX_User_Enable to each axis.  we would like this to be high when an axis is user enabled and low when it is disabled.  I am going to use this on the back end to physically estop disabled axes

**Comment by francotiveron** [comment]
??? This is already there, but tags and functionality

**Comment by pkelm1** [comment]
my mistake, I forgot these were in persistent variables and I didn't see them yesterday.  all good
