### ISSUE TITLE
cue running status

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#24]
we already have status that a cue is loaded but it would be great if we also have status that a cue is running

**Comment by francotiveron** [comment]
New feature
- Loaded 
![image](https://user-images.githubusercontent.com/8280970/84559954-9d062200-ad82-11ea-9274-ab3a86aa8580.png)

- Running
![image](https://user-images.githubusercontent.com/8280970/84559965-b27b4c00-ad82-11ea-9004-8a1a216b86fc.png)
