### ISSUE TITLE
larger contrast for selected vs programed presets

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#25]
Currently a programmed but not selected preset is dark blue and a selected preset is a only slightly lighter blue.  a larger contrast would be great

**Comment by francotiveron** [comment]
Changed lighter color (Blue to Cyan). Might be more difficult to read the name

![image](https://user-images.githubusercontent.com/8280970/129437976-449c3329-08ba-453e-ae80-b970b6533da9.png)
