### ISSUE TITLE
Set new position can only select text

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#26]
in axis setup, you have to actually click on the text of set new position as opposed to pressing anywhere on the button.

**Comment by francotiveron** [comment]
Default Button Background was null, changed to Black

**Comment by pkelm1** [comment]
This isnt a bug for this fix but was discovered when testing it.  if a groups position is changed in the setup screen and then the user presses cancel to exit the setup screen the new position is kept but the groups offset to the other axes is not saved.  I think a good fix for this would be to have a confirmation pop up confirming the user wants to set a new position and upon pressing yes it should toggle the set position variable like it did before but also toggle the new group save variable just like pressing save on the settings page.

it might also be useful to have the confirmation pop up on the axis pages as well but the additional functionality for the group save is not required for an axis
