### ISSUE TITLE
change look of jog velocity slider and label

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#28]
The jog slider looks out of place with the rest of the graphics.  Not sure how hard it would be make it just look like the position bar on the axes rather than looking like a basic windows form

**Comment by francotiveron** [comment]
1) Please confirm that you mean as per the picture
2) Please specify what do you mean with "change the label" in the title

Keep in mind that the jog slider is an input/output widget, the position bar is output only (can't be used to change the value).

![image](https://user-images.githubusercontent.com/8280970/129436208-4e4800ac-606b-4b62-b057-fc677285ea90.png)

**Comment by pkelm1** [comment]
We don't like the look of the jog slider.  If it can just be a solid bar like the position bar you have highlighted I think it would look better.   It should keep the same functionality the slider has, just change the lookPaul KelmOwner / CEOMain: 410-231-7214, Direct: ***@***.*** 
-------- Original message --------From: Franco Tiveron ***@***.***> Date: 8/14/21  2:28 AM  (GMT-05:00) To: francotiveron/Choreo ***@***.***> Cc: pkelm1 ***@***.***>, Author ***@***.***> Subject: Re: [francotiveron/Choreo] change look of jog velocity slider and
  label (#28) 

Please confirm that you mean as per the pcture

**Comment by francotiveron** [comment]
Changed to ScrollBar
![image](https://user-images.githubusercontent.com/8280970/129476728-6a379d15-0e34-42d1-bcbe-3e849d1a0a53.png)
