### ISSUE TITLE
Toggle GVL.Group_XX_save when saving a group

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#30]
when pressing either save button during group edits, I added new variables GVL.Group_XX_save that should be toggled for whatever group is being saved where XX is replaced by the group number, 01, 02, etc

**Comment by francotiveron** [comment]
Please send the updated TwinCAT project

**Comment by pkelm1** [comment]
The current project is kind of a shit show of changes.  I am in the process of cleaning everything up, give me a day and I will get it over

**Comment by francotiveron** [comment]
@pkelm1 
Remember that, as other pulse command, resetting the flag is a PLC program concern

**Comment by pkelm1** [comment]
Yep, I can resetPaul KelmOwner / CEOMain: 410-231-7214, Direct: ***@***.*** 
-------- Original message --------From: Franco Tiveron ***@***.***> Date: 8/20/21  11:50 PM  (GMT-05:00) To: francotiveron/Choreo ***@***.***> Cc: pkelm1 ***@***.***>, Mention ***@***.***> Subject: Re: [francotiveron/Choreo] Toggle GVL.Group_XX_save when saving a
  group (#30) 
@pkelm1
Remember that, as other pulse command, resetting the flag is a PLC program concern
