### ISSUE TITLE
Motor rotations per ft should also write to GVL.Axis_XX_Rotations_Per_Foot

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#31]
I added new variables GVL.Axis_XX_Rotations_Per_Foot for each axis and these should be written to when the value is saved on the axis setup screen.  Also, unless you need it for something, we can get rid of the motor rotations per foot for groups since they are always sim axes and dont actually have a motor.  if need be, we can just make that value 1, but please let me know what you end up doing.

**Comment by francotiveron** [comment]
@pkelm1
Tag now used only for motors. Can be removed for Groups.

**Comment by francotiveron** [comment]
Waiting issue from QuickConverter https://github.com/JohannesMoersch/QuickConverter/issues/14
In alternative, duplicate focusable grid and hide binding to IsGroup/IsMotor

**Comment by francotiveron** [comment]
Help didn't come => controls duplicated
