### ISSUE TITLE
Touch Screen first test

### ISSUE THREAD

**Issue by pkelm1** [francotiveron/Choreo#5]
I put this on the touch screen for the first time today and had a few issues, in no particular order:

- Can't enter axis setup by pressing and holding.  Not sure why this is, it works on the mouse but not the touch

- Can't initiate jogs or moves by swiping, this might just be whatever the other issue is keeping this from happening, or it might be a touch issue as well

- Jog velocity slider is hard to operate.  it seems like a very touch area to operate it.  Can this just become a slider window like the position windows and somehow have a larger touch area.

There may be more but these 3 are keeping me from going much deeper in testing

**Comment by francotiveron** [comment]
Fixed by removing manipulation and resetting stylus tap-and-hold feature
