### ISSUE TITLE
Programable Jog Accel/Decel

### ISSUE THREAD

**Issue by francotiveron** [francotiveron/Choreo#61]
This could be done by adding 2 values to the axis setup screen

**Comment by francotiveron** [comment]
@pkelm you mean something like (please send me the twincat program updated with the necessary variables)

![image](https://user-images.githubusercontent.com/8280970/169635444-de0f79da-cad2-4175-86bb-460d7c0f11a1.png)

**Comment by pkelm1** [comment]
That works for me.  I will work on the program and add variables GVL.Axis_XX_Jog_Accel and GVL.Axis_XX_Jog_Decel for axes 1-24

**Comment by francotiveron** [comment]
Implemented as required
