### ISSUE TITLE
Soft limit enable/disable

### ISSUE THREAD

**Issue by francotiveron** [francotiveron/Choreo#63]
This can just be a checkbox in the axis setup screen

**Comment by francotiveron** [comment]
@pkelm1 This change looks like it needs a new PLC variable. If so, please send me the update PLC program

**Comment by pkelm1** [comment]
It will need a new variable and I will try to get a new program with all variables early this week.  I will create the variable GVL.Axis_XX_Soft_Limit_Enable for axes 1-24

**Comment by francotiveron** [comment]
Implemented as required
