### ISSUE TITLE
Axis tuning variables (p-gain, Jerk, Vel feed forward)

### ISSUE THREAD

**Issue by francotiveron** [francotiveron/Choreo#64]
This would be 3 values in the axis setup page.

**Comment by francotiveron** [comment]
@pkelm1 The easiest thing is to create a new row at the bottom of the settings page, narrowing the previous rows (8 rows instead of the current 7). If this is ok, please
- measurement unit for the 3 data points
- values range check for the 3 data points
- TwinCAT program with the 3 variables

**Comment by pkelm1** [comment]
First I need to change "Vel feed forward" the "reference velocity" 

P-Gain: 
Unit: r/s/r
Range: 0.0001 - 10,000
GVL.Axis_XX_P-Gain

Jerk: 
Unit: r/s2
Range: 0 - 10,000
GVL.Axis_XX_Jerk

Reference Velocity: 
Unit: r/s
Range: 0 - 10,000
GVL.Axis_XX_Ref_Vel

**Comment by francotiveron** [comment]
Implemented as required
