### ISSUE TITLE
Change axis selection check boxes in moves and cues to larger selection buttons

### ISSUE THREAD

**Issue by francotiveron** [francotiveron/Choreo#66]
The main problem here is the small boxes to left of the axis name is hard to press.  if possible, it would be better to be able to press on the entire name

**Comment by francotiveron** [comment]
@pkelm1 Please try clicking on the motor name, it works to me

**Comment by pkelm1** [comment]
Just checked this out and it does work for me as well, I can check on the box and the name.  Would it be possible to put some kind of a box around the whole name and check box so it is more obvious that it all is clickable.  For whatever reason, everyone at the trade show insisted on trying to click the checkbox only

**Comment by francotiveron** [comment]
The outer border has been added, the outcome is acceptable but less than ideal:
1) The clicking area is not the complete box (there are dead zones along the border
2) The box width is variable according to the name length which is a little ugly imo

Improving these to give a better graphical aspect would be costly and would exceed the scope here (make clearer that the click area is not only the square), so I'll leave this to a different issue, if you want to raise it

![image](https://user-images.githubusercontent.com/8280970/170819146-d7886528-be06-4546-9c3e-d5e913700f89.png)
