### ISSUE TITLE
Introduce option for rotational axis

### ISSUE THREAD

**Issue by francotiveron** [francotiveron/Choreo#92]
Axes are originally only linear (engineering motion unit foot and inches).
With this enhancement, the axis and be optionally linear or rotational (engineering motion unit degrees)

**Comment by francotiveron** [comment]
@pkelm1 What would be the engineering unit for rotational axes? 
With degrees, if the position is more than one round, degrees would be > 360
An alternative is rounds and degrees
For example: 1'35'' would mean 1 round and 35 degrees for a rotational axis. This would limit the changes as the visualisation. wouldn't need to change for rotational axes.
In other words we could adopt the following convention:
The symbol ' would mean foot for linear axes and round for rotational
The symbol '' would mean inch for linear axes and degree for rotational
In the setup ages, the unit for velocity would change from fpm to '/m, and for acceleration from fpm2 to '/m2

**Comment by francotiveron** [comment]
@pkelm1  Currently the PLC program uses Rotations_Per_Foot as tag. With the current change it should be changed to Rotations_Per_EU (Engineering Unit), where EU=foot/inch for linear axis, round/degree (or degree only) for rotational.
Please update the PLC program accordingly. During this work, you need to review all places where the tag is used and ensure that there are not evident side effects to this change.
Also, if you need to know in the PLC program whether an axis is linear or rotational (probably you don't), please add a tag per axis

**Comment by pkelm1** [comment]
Originally I was thinking degrees would just compound for rotations so we could move to 270, 360, 720, 1080 or even negative values if required, but I think your approach is fine as long as it is clear that the axis is rotational.  

As for the axis tags, I am currently onsite and am making some minor changes to the back end while getting things setup.  These changes should be finalized in a day or two and I will make a fresh copy with the tag updates for you then.
